import Head from "next/head";
import Link from "next/link";
import Hero from "../components/layout/hero";
import { api } from "~/utils/api";
import dynamic from "next/dynamic";
// Use inter from next/font
import { Inter } from "next/font/google";
import { Suspense, useEffect } from "react";
import { useRouter } from "next/router";
import Navbar from "../components/layout/navbar";
import icon from "../utilities/CC.png";

// Dynamically import the `Wallet` component to make sure we don't get SSR errors
const Login = dynamic(
  () => import("../components/login/login").then((res) => res.default),
  { ssr: false },
);
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // const hello = api.post.hello.useQuery({ text: "from tRPC" });
  const router = useRouter();
  const data = api.user.getUser.useQuery({ wallet_address: "0x12313123" });
  const { mutateAsync, error } = api.user.createUser.useMutation();

  console.log("wallet address user name", data.data?.user?.full_name);
  console.log("wallet address user name", data.data?.user?.wallet_address);

  useEffect(() => {
    let user = localStorage.getItem("user");
    // if (!user) {
    //   router.push("/login");
    // }
  });

  const clicked = () => {
    mutateAsync({
      wallet_address: "0x00012313123123",
      full_name: "Usman rahim",
      email_address: "urkrr@kasdask.com",
    });
  };

  return (
    <>
      <Head>
        <title>Nft Marketplace</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <Suspense fallback={<div>Loading...</div>}>
          <Hero create="Create" classname="hidden" />
        </Suspense>
      </main>
    </>
  );
}
